sudo: required
dist: trusty

language: python
python: '2.7'

install:
  - pip install ansible

before_script:
  - sudo /etc/init.d/postgresql stop

script:
  - ansible-playbook -i "qa," provision/site.yml --connection=local
