sudo: required
dist: trusty
addons:
  hosts:
    - travis-trusty

language: python
python: '3.4'

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt

install:
  - pip3 install ansible

before_script:
  - sudo /etc/init.d/postgresql stop

script:
  - ansible-playbook -i "qa," provision/site.yml --connection=local
